### ISSUE TITLE
Thoughts on minor improvements

### ISSUE THREAD

**Issue by arafalov** [petericebear/solr-configsets#1]
Good initiative, but just a note. **fields** and **types** containers have been deprecated in Solr 6 and are no longer recommended (SOLR-5228).

Also, the solrconfig.xml is rather non-minimal and still includes even the default sections. Getting rid, at least of those and perhaps of large comments sections might help as well.

For comparison, the truly minimal (but not production ready) configset may look like this: https://github.com/arafalov/simplest-solr-config/tree/master/solr-5.5/configset

**Comment by petericebear** [comment]
Thank you @arafalov for your feedback. I will update the config today. 

Can you tell some more about the deprecation of the fields and types?
You may make a PR if you wish, I would surely appriciate it.

**Comment by petericebear** [comment]
Must have been a missing cup of coffee, I understand what you mean and will update it tonight.
Thanks for the headsup

**Comment by petericebear** [comment]
#4be2252 - #13fa28e
I updated the schema's and removed the deprecated list. And the minimal SOLR config is updated as well. Thank you again for your feedback, Alexandre!
